reference/nonfungible-token.scilla
zrcs/zrc-1.md

- Added a `burn` transition that can only be called by either **tokenOwner** or **operator**
- Changed `transfer` transition, removed `from` address from the logic of the transition. Transition can now be called by either **tokenOwner**, **approvedSpender** or **operator**. Added the removal of **approvedSpender** from the `tokenApprovals` map when transfer is executed.

Refactor NFT: Add burn and refactor transfer transitions

---

reference/FungibleToken.scilla

If a contract is calling a subsequent contract in 1 matching branch (success branch), it needs to `throw` in the other branch (error branch) to prevent state errors during chain calls.

fix(zrc-2): Add throw to error branches

---

.github/CODEOWNERS
reference/FungibleToken.scilla
zrcs/zrc-0.md
zrcs/zrc-2.md

There was an inconsistency between the names of the event used in the Transfer transition and TransferFrom transition. As discussed with @evesnow91 , we will update the event name of the Transfer transition to match that of the TransferFrom transition.

Updated the event name for the Transfer transition

---

example/zrc2/deploy.js
reference/FungibleToken-Mintable.scilla
reference/FungibleToken-Operator.scilla
reference/FungibleToken.scilla
zrcs/zrc-2.md

Making `operator` and `default_operator` roles **Optional** in ZRC-2 Fungible token standard.

fix(zrc-2): Make operator and default_operator roles optional

---

example/zrc1/mint.js
reference/nonfungible-token.scilla
zrcs/zrc-1.md

- Remove `token_id` input in the transition `Mint()`
- Add automatic `token_id` counter using `total_supply + 1` in transition `Mint()`

feat(zrc2): Make minting token_ids automatic

---

zrcs/zrc-5.md

This PR introduces ZRC-5, which standardize the naming convention `AddFunds` transition

ZRC-5: Convention for Deposit of ZIL

---

reference/nonfungible-token.scilla

`token_id` count is bugged as it takes reference from `total_supply`. If `token_id = 1` is Burned while `total_supply = 2`. The `Mint` procedure will be broken and unusable. Solution is to add an additional field `token_id_count` that does not decrease, once a `token_id` is used, it will not be able to be used ever again.

fix(zrc-1): token_id bug

---

zrcs/zrc-5.md

This is now a standard convention. Hence, transiting the status to approved. Long overdue

chore(zrc5): transit zrc5 to approved

---

reference/nonfungible-token.scilla

Convert transition BatchMint() to multi-address mint.
You can now mint tokens and send them to multiple different addresses.
Good for airdropping NFTs.

Convert transition BatchMint() to multi-address mint

---

reference/multisig_wallet.scilla
zrcs/zrc-5.md

The issues fixed in `multisig_wallet.scilla` are discovered using @tramhnt99's dead code detector recently merged in Scilla's master. There is one more unused library entry (`f`) in `multisig_wallet.scilla` but I'd prefer to remove it along with some refactoring of the map insertion code (switch `Bool` with `Unit` type, like in the Fungible Token contract).

Dead code and some syntax fixes

---

zrcs/zrc-1.md

This PR fixes the incorrect descriptions in ZRC-1 as the following:
- approved sender -> approved spender (CodeNotApprovedSpenderOrOperator)
- address of the approved_spender -> address of the operator (SetApprovalForAllSuccessCallBack)

ZRC-1 fix description

---

reference/nonfungible-token.scilla

This PR checks if the token exists for `GetApproved()`.
If the token doesn't exist, then it throws `CodeNotFound` error.
The current `GetApproved()` throws `CodeNotApproved` error if the token doesn't exist.
This can be misleading.

fix(zrc1): token must exist for GetApproved

---

LICENSE

This PR adds MIT license.
The reference contracts are MIT licensed such that developers can use them freely.

chore: MIT license

---

reference/nonfungible-token.scilla

This PR makes only token owners be the `_sender` for `SetApprovalForAll()`.
If some random user, who doesn't own any token, tries to add an operator it will throw `CodeNotTokenOwner`.
Currently, anyone who doesn't have any token can set anyone as an operator with `SetApprovalForAll()` and create some garbage data in the contract. Only token owners should be able to add an operator.

fix(zrc1): only token owner can add an operator

---

reference/zrc6.scilla
tests/zrc6/zrc6.mint.test.ts
zrcs/zrc-6.md

This PR validates the destination for minting.
The destination must not be zero address or `_this_address`
- [Ethereum Smart Contract Best Practices - Token Implementation Best Practice](https://github.com/ConsenSys/smart-contract-best-practices/blob/master/docs/tokens.md)

feat(zrc6): validate destination for Minting

---

reference/zrc6.scilla

By having the guard clause RequireNotPaused in procedures, batch operations result in multiple (wasted) calls to `RequireNotPaused`. When operations occur in large batches, this is a waste of gas fees and network efficiency.
Fixes issue #124 
Old procedures with `RequireNotPaused`:
- MintToken
- BurnToken
- TransferToken
New transitions with `RequireNotPaused`:
- Mint
- BatchMint
- Burn
- BatchBurn
- TransferFrom
- BatchTransferFrom

Fix: optimise zrc6 `RequireNotPaused` calls

---

tests/zrc6/config.ts
tests/zrc6/testutil.ts
tests/zrc6/testutils.test.ts
tests/zrc6/zrc6.approval.test.ts
tests/zrc6/zrc6.token.test.ts

This PR uses `getJSONParams` instead of `useContractInfo`.
In this way, test cases are more consistent and readable. 
Also, it removes Scilla Checker dependency.

test: use json params util

---

zrcs/zrc-6.md

This PR adds the missing description for `start_id`, `end_id` in the BatchMint event.

docs: description for start_id, end_id

---

reference/zrc6.scilla
tests/zrc6/zrc6.approval.test.ts
tests/zrc6/zrc6.mint.test.ts
zrcs/zrc-6.md

This PR changes `BatchBurn`, `BatchTransferFrom` to emit an event per item to include the previous token owner address in the event. It's more complete and consistent because `Burn` and `TransferFrom` events provide the previous token owner address.
|  N  | Current BatchBurn (cumulative_gas) | New BatchBurn with Multiple Events (cumulative_gas) |
| :-: | ---------------------------------- | --------------------------------------------------- |
| 10  | 766                                | 885                                                 |
| 50  | 2137                               | 2766                                                |
| 100 | 3843                               | 5110                                                |
This approach is more gas-efficient way, compared to …

feat: multiple events for batch ops

---

zrcs/zrc-6.md

This PR fixes the Error Code description by replacing `Error event` -> `Error exception`.
scilla-doc explains error event with the following example.
https://scilla.readthedocs.io/en/latest/scilla-by-example.html?highlight=error%20event%20#procedures
```
procedure DonationEvent (failure : Bool, error_code : Int32)
match failure with
| False =>
e = {_eventname : "DonationSuccess"; donor : _sender;
amount : _amount; code : accepted_code};
event e
| True =>
e = {_eventname : "DonationFailure"; donor : _sender;
amount : _amount; code : error_code};
event e
end
end
```

docs(zrc-6): event -> exception

---

zrcs/zrc-1.md

This PR fixes the Error Code description by replacing `Error event` -> `Error exception`.

docs(zrc-1): event -> exception

---

reference/zrc6.scilla

Small bug fix to to reference ZRC6 implementation to delete `token_uris` of a burnt token

small fix to delete token_uris on burn

---

reference/zrc6.scilla
tests/zrc6/zrc6.approval.test.ts
zrcs/zrc-6.md

This PR includes `token_owner` as callback and event parameter for the following transitions:
- `SetSpender`
- `AddOperator`
- `RemoveOperator`
Also, it fixes the `SetSpender` callback name (`ZRC6_AddSpenderCallback`  -> `ZRC6_SetSpenderCallback`).

feat(zrc6): token_owner param

---

reference/zrc6.scilla
tests/zrc6/zrc6.approval.test.ts
zrcs/zrc-6.md

For backward compatibility, this PR removes `token_owner` from callback params of the following transitions:
- `SetSpender`
- `AddOperator`
- `RemoveOperator`
- #152

fix: callback param

---

zrcs/zrc-6.md

This PR fixes typo: `zero address. i.e.,` -> `zero address i.e.,`.

docs(zrc6): fix typo

---

zrcs/zrc-7.md

This PR includes an example for data url with utf-8 encoding.
```js
encodeURIComponent(JSON.stringify({
"name": "Creature #101",
"resources": [
{ "uri": "ipfs://QmZILGa7zXUbixvYJpgkRkaSCYEBtSwgVtfzkoD3YkNsE1" }
]
}))
```
`data:application/json,%7B%22name%22%3A%22Creature%20%23101%22%2C%22resources%22%3A%5B%7B%22uri%22%3A%22ipfs%3A%2F%2FQmZILGa7zXUbixvYJpgkRkaSCYEBtSwgVtfzkoD3YkNsE1%22%7D%5D%7D`

docs(zrc7): data url with utf-8 encoding

---

zrcs/zrc-6.md

This PR fixes and consolidates links of Ethereum Smart Contract Best Practices.

docs(zrc6): fix reference link

---

zrcs/zrc-7.md

This PR exemplifies token URIs with contract state.

docs(zrc7): exemplify token URIs with contract state
