- zrcs/zrc-0.md
> Update ZRC1 broken discord link

- example/zrc2/auth_operator.js
- example/zrc2/burn.js
- example/zrc2/decrease_allowance.js
- example/zrc2/increase_allowance.js
- example/zrc2/is_operator_for.js
- example/zrc2/mint.js
- example/zrc2/operator_send.js
- example/zrc2/revoke_operator.js
- example/zrc2/transfer.js
- example/zrc2/transfer_from.js
This pr is to fix the passing parameters while doing contract calls for the example projects.
> fix(example): recovery default parameters while calling contract

- README.md
> chore(readme): Fixed expired discord link

- example/zrc2/FungibleToken.scilla
This pr is to make js project use the latest FungibleToken contract.
> chore: change to use  the latest FungibleToken contract

- .github/CODEOWNERS
- zrcs/zrc-0.md
> Add Arnav Vohra as an editor

- reference/FungibleToken-Mintable.scilla
- reference/FungibleToken-Operator.scilla
- reference/FungibleToken.scilla
Referring to https://github.com/Zilliqa/staking-contract/issues/166
> fix(zrc): audit fixes for inconsistent behaviour

- reference/nonfungible-token.scilla
Allow for batch minting of NFTs.
No change to ZRC1 required, backwards compatible.
> feat: Add BatchMint() transition

- reference/nonfungible-token.scilla
- zrcs/zrc-1.md
- Add a matching check for `to` and `approved_spender` in the `SetApprove()` transition
- Add more params to `IsApprovedForAllCallBack` msg.
> fix(zrc1): Add check for to with approved_spender in SetApprove()

- zrcs/zrc-1.md
> fix(zrc1): TransferFrom broken table format fix

- zrcs/zrc-3.md
> fix(zrc3): zrc number and title

- reference/nonfungible-token.scilla
>  refactor(zrc1): procedure names

- .travis.yml
- ci_build.sh
> ci: check contracts

- zrcs/zrc-1.md
This PR documents the `token_id_count` field.
> docs: token_id_count field

- .github/CODEOWNERS
Update code owner to reflect what is stated on ZRC-0
ref: #114
> Update code owner 

- zrcs/zrc-0.md
> [ZRC-0] edit ZRC editors

- zrcs/zrc-1.md
- zrcs/zrc-2.md
- zrcs/zrc-5.md
These standards are now widely adopted and considered "Implemented"
> [ZRC-1/ZRC-2/ZRC-5] Transit to "Implemented"

- zrcs/zrc-6.md
This PR fixes the description for batch mint requirements.
> docs(zrc6): description for batch mint requirements

- zrcs/zrc-6.md
This PR makes the motivation of concatenated token URI  more specific.
> docs: motivation of concatenated token URI

- README.md
This PR adds badges for CI and License.
> docs: badges for CI and License

- zrcs/zrc-6.md
> docs: finalize zrc-6

- README.md
This PR modifies header and description.
> docs: header

- README.md
This PR provides the ZRC table with links.
> docs: zrc table

- package-lock.json
- package.json
- tests/zrc6/testutils.ts
- tests/zrc6/zrc6.approval.test.ts
- tests/zrc6/zrc6.mint.test.ts
- tests/zrc6/zrc6.token.test.ts
This PR uses `@zilliqa-js/scilla-json-utils` v0.2.
> test: scilla-json-utils v0.2

- README.md
This PR documents the following:
- contract testing
- license
> docs: contract testing, license

- package.json
This PR removes the unused argument `CONTAINER`.
> chore: remove unused argument

- package-lock.json
- package.json
This PR uses zilliqa-js v3.3.4.
> build: zilliqa-js-v3.3.4

- tests/zrc6/zrc6.token.test.ts
> test(zrc6): fix typo

- zrcs/zrc-6.md
This PR includes data url and ZRC-7 in Abstract.
> docs(zrc6): zrc-7 and data url

- zrcs/zrc-7.md
Based on the feedback from community, this PR improves the following for ZRC-7:
- multiple resources
- `mime_type` and `integrity` for attributes 
- `transitions` field
- data url
> docs(zrc7): improvements based on the feedback

- zrcs/zrc-7.md
This PR updates the other property example in ZRC-7.
> docs(zrc7): other property example

- zrcs/zrc-7.md
This PR updates ZRC-7 status: `Ready` -> `Approved`
> docs(zrc7): Ready -> Approved

- tests/zrc6/config.ts
- tests/zrc6/zrc6.mint.test.ts
- tests/zrc6/zrc6.token.test.ts
This PR refactors config for zrc-6 tests.
> test(zrc6): refactor config

- zrcs/zrc-7.md
This PR elaborates the no base uri case.
> docs(zrc7): elaborate no base uri case

- zrcs/zrc-7.md
This PR explains why the token URI optimization with base URI can be space and gas efficient.
> docs(zrc7): space-efficient, gas-efficient

- zrcs/zrc-6.md
- zrcs/zrc-7.md
This PR updates the ZRC-6 and the ZRC-7 status.
> docs: zrc-6, zrc-7 status

- package.json
- tests/zrc6/zrc6.token.test.ts
This PR changes constraint violation tests. Also, it runs tests in sequentially.
> test(zrc-6): constraint violation
